/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Dataset */
        post: operations["upload_dataset_datasets_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset */
        get: operations["get_dataset_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        /** Delete Dataset */
        delete: operations["delete_dataset_datasets__dataset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset Columns */
        get: operations["get_dataset_columns_datasets__dataset_id__columns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset Quality */
        get: operations["get_dataset_quality_datasets__dataset_id__quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset Lineage */
        get: operations["get_dataset_lineage_datasets__dataset_id__lineage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset Preview */
        get: operations["get_dataset_preview_datasets__dataset_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Kpi Summary */
        get: operations["get_kpi_summary_datasets__dataset_id__kpis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/kpis/breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Breakdown */
        get: operations["get_breakdown_datasets__dataset_id__kpis_breakdown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/kpis/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trend */
        get: operations["get_trend_datasets__dataset_id__kpis_trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_dataset_datasets_upload_post */
        Body_upload_dataset_datasets_upload_post: {
            /** File */
            file: string;
            /** Dataset Name */
            dataset_name?: string | null;
        };
        /** BreakdownItemOut */
        BreakdownItemOut: {
            /** Category */
            category: string;
            /** Value */
            value: number;
        };
        /** BreakdownOut */
        BreakdownOut: {
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /** Group By */
            group_by: string;
            /** Metric */
            metric: string | null;
            /** Aggregation */
            aggregation: string;
            /** Items */
            items: components["schemas"]["BreakdownItemOut"][];
            /** Total Categories */
            total_categories: number;
        };
        /** ColumnInfo */
        ColumnInfo: {
            /** Position */
            position: number;
            /** Original Name */
            original_name: string;
            /** Column Name */
            column_name: string;
            /** Detected Type */
            detected_type: string;
            /** Nullable */
            nullable: boolean;
            /** Null Count */
            null_count: number;
            /** Distinct Count */
            distinct_count: number;
            /** Min Value */
            min_value: string | null;
            /** Max Value */
            max_value: string | null;
            /** Mean Value */
            mean_value: number | null;
            /** Sample Values */
            sample_values: unknown[] | null;
        };
        /** DatasetDetail */
        DatasetDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Original Filename */
            original_filename: string;
            /** File Type */
            file_type: string;
            /** Storage Schema */
            storage_schema: string;
            /** Storage Table Name */
            storage_table_name: string;
            /** Row Count */
            row_count: number;
            /** Column Count */
            column_count: number;
            /** Quality Score */
            quality_score: number;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Columns */
            columns: components["schemas"]["ColumnInfo"][];
        };
        /** DatasetSummary */
        DatasetSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Original Filename */
            original_filename: string;
            /** File Type */
            file_type: string;
            /** Storage Schema */
            storage_schema: string;
            /** Storage Table Name */
            storage_table_name: string;
            /** Row Count */
            row_count: number;
            /** Column Count */
            column_count: number;
            /** Quality Score */
            quality_score: number;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** App Name */
            app_name: string;
            /** App Env */
            app_env: string;
            /** Database */
            database: string;
        };
        /** KpiSummaryOut */
        KpiSummaryOut: {
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /** Kpis */
            kpis: components["schemas"]["KpiValueOut"][];
            /** Numeric Columns */
            numeric_columns: string[];
            /** Suggested Breakdown Columns */
            suggested_breakdown_columns: string[];
            /** Suggested Trend Columns */
            suggested_trend_columns: string[];
        };
        /** KpiValueOut */
        KpiValueOut: {
            /** Column */
            column: string;
            /** Kind */
            kind: string;
            /** Value */
            value: number | null;
        };
        /** LineageEventOut */
        LineageEventOut: {
            /** Step */
            step: string;
            /** Status */
            status: string;
            /** Detail */
            detail: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LineageOut */
        LineageOut: {
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /** Events */
            events: components["schemas"]["LineageEventOut"][];
        };
        /** PreviewOut */
        PreviewOut: {
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /** Columns */
            columns: string[];
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
        };
        /** QualityIssueOut */
        QualityIssueOut: {
            /** Rule */
            rule: string;
            /** Column Name */
            column_name: string | null;
            /** Severity */
            severity: string;
            /** Message */
            message: string;
            /** Score Impact */
            score_impact: number;
        };
        /** QualityReportOut */
        QualityReportOut: {
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /** Quality Score */
            quality_score: number;
            /** Issues */
            issues: components["schemas"]["QualityIssueOut"][];
        };
        /** TrendOut */
        TrendOut: {
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /** Date Column */
            date_column: string;
            /** Metric */
            metric: string;
            /** Granularity */
            granularity: string;
            /** Aggregation */
            aggregation: string;
            /** Points */
            points: components["schemas"]["TrendPointOut"][];
        };
        /** TrendPointOut */
        TrendPointOut: {
            /** Period */
            period: string;
            /** Value */
            value: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    upload_dataset_datasets_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_dataset_datasets_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_datasets_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dataset_datasets__dataset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_columns_datasets__dataset_id__columns_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_quality_datasets__dataset_id__quality_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_lineage_datasets__dataset_id__lineage_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_preview_datasets__dataset_id__preview_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_kpi_summary_datasets__dataset_id__kpis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_breakdown_datasets__dataset_id__kpis_breakdown_get: {
        parameters: {
            query: {
                group_by: string;
                metric?: string | null;
                agg?: string;
            };
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BreakdownOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trend_datasets__dataset_id__kpis_trend_get: {
        parameters: {
            query: {
                date_column: string;
                metric: string;
                granularity?: string;
                agg?: string;
            };
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
