/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_users__user_id__get"];
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["delete_user_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_users__user_id__patch"];
        trace?: never;
    };
    "/users/{user_id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign Roles */
        post: operations["assign_roles_users__user_id__roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Roles */
        get: operations["list_roles_roles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Permissions */
        get: operations["list_permissions_permissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audit Logs */
        get: operations["get_audit_logs_audit_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Dataset */
        post: operations["upload_dataset_datasets_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset */
        get: operations["get_dataset_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        /** Delete Dataset */
        delete: operations["delete_dataset_datasets__dataset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset Columns */
        get: operations["get_dataset_columns_datasets__dataset_id__columns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset Quality */
        get: operations["get_dataset_quality_datasets__dataset_id__quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset Lineage */
        get: operations["get_dataset_lineage_datasets__dataset_id__lineage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset Preview */
        get: operations["get_dataset_preview_datasets__dataset_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Kpi Summary */
        get: operations["get_kpi_summary_datasets__dataset_id__kpis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/kpis/breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Breakdown */
        get: operations["get_breakdown_datasets__dataset_id__kpis_breakdown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/kpis/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trend */
        get: operations["get_trend_datasets__dataset_id__kpis_trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/ml/suitability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Suitability */
        get: operations["get_suitability_datasets__dataset_id__ml_suitability_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ml/train/classification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Train Classification */
        post: operations["train_classification_ml_train_classification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ml/train/forecasting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Train Forecasting */
        post: operations["train_forecasting_ml_train_forecasting_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ml/train/segmentation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Train Segmentation */
        post: operations["train_segmentation_ml_train_segmentation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ml/train/anomaly-detection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Train Anomaly Detection */
        post: operations["train_anomaly_detection_ml_train_anomaly_detection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ml/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_ml_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ml/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_ml_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ml/runs/{run_id}/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict */
        post: operations["predict_ml_runs__run_id__predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnomalyPredictionOut */
        AnomalyPredictionOut: {
            /** Row Index */
            row_index: number;
            /** Anomaly Score */
            anomaly_score: number;
            /** Is Anomaly */
            is_anomaly: boolean;
        };
        /** AnomalyRecordOut */
        AnomalyRecordOut: {
            /** Row Index */
            row_index: number;
            /** Anomaly Score */
            anomaly_score: number;
            /** Is Anomaly */
            is_anomaly: boolean;
            /** Values */
            values: {
                [key: string]: unknown;
            };
        };
        /** AnomalyResultsOut */
        AnomalyResultsOut: {
            /** Feature Columns */
            feature_columns: string[];
            /** Contamination */
            contamination: number;
            /** Anomaly Count */
            anomaly_count: number;
            /** Anomaly Percentage */
            anomaly_percentage: number;
            /** Anomalous Records */
            anomalous_records: components["schemas"]["AnomalyRecordOut"][];
            /** Score Summary */
            score_summary: {
                [key: string]: number;
            };
            /** Random Seed */
            random_seed: number;
            /** Was Sampled */
            was_sampled: boolean;
        };
        /** AnomalyTrainRequest */
        AnomalyTrainRequest: {
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /** Feature Columns */
            feature_columns?: string[] | null;
            /**
             * Contamination
             * @default 0.05
             */
            contamination: number;
            /** Random Seed */
            random_seed?: number | null;
        };
        /** AssignRolesRequest */
        AssignRolesRequest: {
            /** Role Names */
            role_names: string[];
        };
        /** AuditLogOut */
        AuditLogOut: {
            /** Id */
            id: number;
            /** User Id */
            user_id: string | null;
            /** User Email */
            user_email: string | null;
            /** Action */
            action: string;
            /** Resource Type */
            resource_type: string | null;
            /** Resource Id */
            resource_id: string | null;
            /** Event Metadata */
            event_metadata: {
                [key: string]: unknown;
            } | null;
            /** Ip Address */
            ip_address: string | null;
            /** User Agent */
            user_agent: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AuditLogPage */
        AuditLogPage: {
            /** Items */
            items: components["schemas"]["AuditLogOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Body_upload_dataset_datasets_upload_post */
        Body_upload_dataset_datasets_upload_post: {
            /** File */
            file: string;
            /** Dataset Name */
            dataset_name?: string | null;
        };
        /** BreakdownItemOut */
        BreakdownItemOut: {
            /** Category */
            category: string;
            /** Value */
            value: number;
        };
        /** BreakdownOut */
        BreakdownOut: {
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /** Group By */
            group_by: string;
            /** Metric */
            metric: string | null;
            /** Aggregation */
            aggregation: string;
            /** Items */
            items: components["schemas"]["BreakdownItemOut"][];
            /** Total Categories */
            total_categories: number;
        };
        /** CandidateModelMetrics */
        CandidateModelMetrics: {
            /** Model Name */
            model_name: string;
            /** Metrics */
            metrics: {
                [key: string]: number;
            };
        };
        /** ClassificationPredictionOut */
        ClassificationPredictionOut: {
            /** Row Index */
            row_index: number;
            /** Predicted */
            predicted: string;
            /** Probability */
            probability: number;
        };
        /** ClassificationResultsOut */
        ClassificationResultsOut: {
            /** Target Column */
            target_column: string;
            /** Feature Columns */
            feature_columns: string[];
            /** Class Distribution */
            class_distribution: {
                [key: string]: number;
            };
            /** Candidate Models */
            candidate_models: components["schemas"]["CandidateModelMetrics"][];
            /** Selected Model */
            selected_model: string;
            /** Primary Metric */
            primary_metric: string;
            /** Primary Metric Rationale */
            primary_metric_rationale: string;
            /** Metrics */
            metrics: {
                [key: string]: number;
            };
            confusion_matrix: components["schemas"]["ConfusionMatrixOut"];
            /** Feature Importance */
            feature_importance: components["schemas"]["FeatureImportanceOut"][];
            /** Sample Predictions */
            sample_predictions: components["schemas"]["ClassificationSamplePrediction"][];
            /** Test Size */
            test_size: number;
            /** Random Seed */
            random_seed: number;
            /** Was Sampled */
            was_sampled: boolean;
        };
        /** ClassificationSamplePrediction */
        ClassificationSamplePrediction: {
            /** Row Index */
            row_index: number;
            /** Actual */
            actual: string;
            /** Predicted */
            predicted: string;
            /** Probability */
            probability: number;
        };
        /** ClassificationTrainRequest */
        ClassificationTrainRequest: {
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /** Target Column */
            target_column: string;
            /** Feature Columns */
            feature_columns?: string[] | null;
            /**
             * Test Size
             * @default 0.25
             */
            test_size: number;
            /** Random Seed */
            random_seed?: number | null;
        };
        /** ClusterProfileOut */
        ClusterProfileOut: {
            /** Cluster */
            cluster: number;
            /** Size */
            size: number;
            /** Feature Means */
            feature_means: {
                [key: string]: number;
            };
        };
        /** ColumnInfo */
        ColumnInfo: {
            /** Position */
            position: number;
            /** Original Name */
            original_name: string;
            /** Column Name */
            column_name: string;
            /** Detected Type */
            detected_type: string;
            /** Nullable */
            nullable: boolean;
            /** Null Count */
            null_count: number;
            /** Distinct Count */
            distinct_count: number;
            /** Min Value */
            min_value: string | null;
            /** Max Value */
            max_value: string | null;
            /** Mean Value */
            mean_value: number | null;
            /** Sample Values */
            sample_values: unknown[] | null;
        };
        /** ConfusionMatrixOut */
        ConfusionMatrixOut: {
            /** Labels */
            labels: string[];
            /** Matrix */
            matrix: number[][];
        };
        /** DatasetDetail */
        DatasetDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Original Filename */
            original_filename: string;
            /** File Type */
            file_type: string;
            /** Storage Schema */
            storage_schema: string;
            /** Storage Table Name */
            storage_table_name: string;
            /** Row Count */
            row_count: number;
            /** Column Count */
            column_count: number;
            /** Quality Score */
            quality_score: number;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Columns */
            columns: components["schemas"]["ColumnInfo"][];
        };
        /** DatasetSuitabilityOut */
        DatasetSuitabilityOut: {
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /** Row Count */
            row_count: number;
            /** Tasks */
            tasks: components["schemas"]["TaskSuitabilityOut"][];
        };
        /** DatasetSummary */
        DatasetSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Original Filename */
            original_filename: string;
            /** File Type */
            file_type: string;
            /** Storage Schema */
            storage_schema: string;
            /** Storage Table Name */
            storage_table_name: string;
            /** Row Count */
            row_count: number;
            /** Column Count */
            column_count: number;
            /** Quality Score */
            quality_score: number;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** FeatureImportanceOut */
        FeatureImportanceOut: {
            /** Feature */
            feature: string;
            /** Importance */
            importance: number;
            /** Direction */
            direction?: string | null;
        };
        /** ForecastPointOut */
        ForecastPointOut: {
            /** Period */
            period: string;
            /** Value */
            value: number;
            /** Lower */
            lower?: number | null;
            /** Upper */
            upper?: number | null;
        };
        /** ForecastResultsOut */
        ForecastResultsOut: {
            /** Datetime Column */
            datetime_column: string;
            /** Target Column */
            target_column: string;
            /** Horizon */
            horizon: number;
            /** Candidate Models */
            candidate_models: components["schemas"]["CandidateModelMetrics"][];
            /** Selected Model */
            selected_model: string;
            /** Primary Metric */
            primary_metric: string;
            /** Metrics */
            metrics: {
                [key: string]: number;
            };
            /** Historical */
            historical: components["schemas"]["TimeSeriesPointOut"][];
            /** Forecast */
            forecast: components["schemas"]["ForecastPointOut"][];
            /** Has Confidence Interval */
            has_confidence_interval: boolean;
            /** Random Seed */
            random_seed: number;
        };
        /** ForecastTrainRequest */
        ForecastTrainRequest: {
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /** Datetime Column */
            datetime_column: string;
            /** Target Column */
            target_column: string;
            /**
             * Horizon
             * @default 14
             */
            horizon: number;
            /** Random Seed */
            random_seed?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** App Name */
            app_name: string;
            /** App Env */
            app_env: string;
            /** Database */
            database: string;
        };
        /** KpiSummaryOut */
        KpiSummaryOut: {
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /** Kpis */
            kpis: components["schemas"]["KpiValueOut"][];
            /** Numeric Columns */
            numeric_columns: string[];
            /** Suggested Breakdown Columns */
            suggested_breakdown_columns: string[];
            /** Suggested Trend Columns */
            suggested_trend_columns: string[];
        };
        /** KpiValueOut */
        KpiValueOut: {
            /** Column */
            column: string;
            /** Kind */
            kind: string;
            /** Value */
            value: number | null;
        };
        /** LineageEventOut */
        LineageEventOut: {
            /** Step */
            step: string;
            /** Status */
            status: string;
            /** Detail */
            detail: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LineageOut */
        LineageOut: {
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /** Events */
            events: components["schemas"]["LineageEventOut"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MLRunOut */
        MLRunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /**
             * Task Type
             * @enum {string}
             */
            task_type: "classification" | "forecasting" | "segmentation" | "anomaly_detection";
            /** Model Name */
            model_name: string;
            /** Status */
            status: string;
            /** Configuration */
            configuration: {
                [key: string]: unknown;
            };
            /** Created By */
            created_by: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
        };
        /** MLRunResultsOut */
        MLRunResultsOut: {
            run: components["schemas"]["MLRunOut"];
            /** Results */
            results: components["schemas"]["ClassificationResultsOut"] | components["schemas"]["ForecastResultsOut"] | components["schemas"]["SegmentationResultsOut"] | components["schemas"]["AnomalyResultsOut"];
        };
        /** PermissionOut */
        PermissionOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
        };
        /** PredictRequest */
        PredictRequest: {
            /** Horizon */
            horizon?: number | null;
        };
        /** PredictionResponseOut */
        PredictionResponseOut: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Task Type
             * @enum {string}
             */
            task_type: "classification" | "forecasting" | "segmentation" | "anomaly_detection";
            /** Predictions */
            predictions: components["schemas"]["ClassificationPredictionOut"][] | components["schemas"]["SegmentationPredictionOut"][] | components["schemas"]["AnomalyPredictionOut"][] | components["schemas"]["ForecastPointOut"][];
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
        };
        /** PreviewOut */
        PreviewOut: {
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /** Columns */
            columns: string[];
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
        };
        /** QualityIssueOut */
        QualityIssueOut: {
            /** Rule */
            rule: string;
            /** Column Name */
            column_name: string | null;
            /** Severity */
            severity: string;
            /** Message */
            message: string;
            /** Score Impact */
            score_impact: number;
        };
        /** QualityReportOut */
        QualityReportOut: {
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /** Quality Score */
            quality_score: number;
            /** Issues */
            issues: components["schemas"]["QualityIssueOut"][];
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
        };
        /** RoleOut */
        RoleOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
        };
        /** SegmentationPredictionOut */
        SegmentationPredictionOut: {
            /** Row Index */
            row_index: number;
            /** Cluster */
            cluster: number;
        };
        /** SegmentationResultsOut */
        SegmentationResultsOut: {
            /** Feature Columns */
            feature_columns: string[];
            /** N Clusters */
            n_clusters: number;
            /** Silhouette Score */
            silhouette_score: number;
            /** Cluster Sizes */
            cluster_sizes: {
                [key: string]: number;
            };
            /** Cluster Profiles */
            cluster_profiles: components["schemas"]["ClusterProfileOut"][];
            /** Cluster Centers */
            cluster_centers: number[][];
            /** Random Seed */
            random_seed: number;
            /** Was Sampled */
            was_sampled: boolean;
        };
        /** SegmentationTrainRequest */
        SegmentationTrainRequest: {
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /** Feature Columns */
            feature_columns?: string[] | null;
            /**
             * N Clusters
             * @default 4
             */
            n_clusters: number;
            /** Random Seed */
            random_seed?: number | null;
        };
        /** TaskSuitabilityOut */
        TaskSuitabilityOut: {
            /**
             * Task Type
             * @enum {string}
             */
            task_type: "classification" | "forecasting" | "segmentation" | "anomaly_detection";
            /** Suitable */
            suitable: boolean;
            /** Reasons */
            reasons: string[];
            /** Suggested Target Columns */
            suggested_target_columns?: string[];
            /** Suggested Datetime Columns */
            suggested_datetime_columns?: string[];
            /** Suggested Feature Columns */
            suggested_feature_columns?: string[];
        };
        /** TimeSeriesPointOut */
        TimeSeriesPointOut: {
            /** Period */
            period: string;
            /** Value */
            value: number;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** TrendOut */
        TrendOut: {
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /** Date Column */
            date_column: string;
            /** Metric */
            metric: string;
            /** Granularity */
            granularity: string;
            /** Aggregation */
            aggregation: string;
            /** Points */
            points: components["schemas"]["TrendPointOut"][];
        };
        /** TrendPointOut */
        TrendPointOut: {
            /** Period */
            period: string;
            /** Value */
            value: number;
        };
        /** UpdateUserRequest */
        UpdateUserRequest: {
            /** Full Name */
            full_name?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /**
         * UserAdminOut
         * @description A user as seen by an admin in the user-management UI.
         */
        UserAdminOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Is Active */
            is_active: boolean;
            /** Roles */
            roles: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Roles */
            roles: string[];
            /** Permissions */
            permissions: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_users_users_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAdminOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_roles_users__user_id__roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRolesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roles_roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleOut"][];
                };
            };
        };
    };
    list_permissions_permissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionOut"][];
                };
            };
        };
    };
    get_audit_logs_audit_logs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                action?: string | null;
                resource_type?: string | null;
                user_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_dataset_datasets_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_dataset_datasets_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_datasets_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dataset_datasets__dataset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_columns_datasets__dataset_id__columns_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_quality_datasets__dataset_id__quality_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_lineage_datasets__dataset_id__lineage_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_preview_datasets__dataset_id__preview_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_kpi_summary_datasets__dataset_id__kpis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_breakdown_datasets__dataset_id__kpis_breakdown_get: {
        parameters: {
            query: {
                group_by: string;
                metric?: string | null;
                agg?: string;
            };
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BreakdownOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trend_datasets__dataset_id__kpis_trend_get: {
        parameters: {
            query: {
                date_column: string;
                metric: string;
                granularity?: string;
                agg?: string;
            };
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_suitability_datasets__dataset_id__ml_suitability_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSuitabilityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    train_classification_ml_train_classification_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassificationTrainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MLRunResultsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    train_forecasting_ml_train_forecasting_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForecastTrainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MLRunResultsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    train_segmentation_ml_train_segmentation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SegmentationTrainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MLRunResultsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    train_anomaly_detection_ml_train_anomaly_detection_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnomalyTrainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MLRunResultsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_ml_runs_get: {
        parameters: {
            query?: {
                dataset_id?: string | null;
                task_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MLRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_ml_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MLRunResultsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_ml_runs__run_id__predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionResponseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
