"""create app_metadata table

Revision ID: 43d2212be27c
Revises: 
Create Date: 2026-08-11 15:41:33.371843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d2212be27c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Not autogenerated: enable pgvector before anything that will later
    # depend on it (embedding columns arrive in Phase 7). Doing this in the
    # first migration proves the pgvector/pgvector:pg16 image + Alembic
    # pipeline actually supports it, ahead of needing it for real.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_metadata',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_metadata')
    # ### end Alembic commands ###

    op.execute("DROP EXTENSION IF EXISTS vector")
