"""create model versions and monitoring events tables

Revision ID: 71e77dd69b3e
Revises: d6fc0f04ea52
Create Date: 2026-08-12 11:12:53.559757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71e77dd69b3e'
down_revision: Union[str, Sequence[str], None] = 'd6fc0f04ea52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ml_run_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=30), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('artifact_checksum', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('promoted_by', sa.UUID(), nullable=True),
    sa.Column('promoted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ml_run_id'], ['ml_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promoted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'task_type', 'version_number', name='uq_model_version_family_number'),
    sa.UniqueConstraint('ml_run_id')
    )
    op.create_index(op.f('ix_model_versions_dataset_id'), 'model_versions', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_model_versions_status'), 'model_versions', ['status'], unique=False)
    op.create_index(op.f('ix_model_versions_task_type'), 'model_versions', ['task_type'], unique=False)
    op.create_index('uq_model_version_one_production_per_family', 'model_versions', ['dataset_id', 'task_type'], unique=True, postgresql_where=sa.text("status = 'production'"))
    op.create_table('ml_monitoring_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_monitoring_events_created_at'), 'ml_monitoring_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_ml_monitoring_events_dataset_id'), 'ml_monitoring_events', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_ml_monitoring_events_event_type'), 'ml_monitoring_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_ml_monitoring_events_model_version_id'), 'ml_monitoring_events', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_ml_monitoring_events_severity'), 'ml_monitoring_events', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_monitoring_events_severity'), table_name='ml_monitoring_events')
    op.drop_index(op.f('ix_ml_monitoring_events_model_version_id'), table_name='ml_monitoring_events')
    op.drop_index(op.f('ix_ml_monitoring_events_event_type'), table_name='ml_monitoring_events')
    op.drop_index(op.f('ix_ml_monitoring_events_dataset_id'), table_name='ml_monitoring_events')
    op.drop_index(op.f('ix_ml_monitoring_events_created_at'), table_name='ml_monitoring_events')
    op.drop_table('ml_monitoring_events')
    op.drop_index('uq_model_version_one_production_per_family', table_name='model_versions', postgresql_where=sa.text("status = 'production'"))
    op.drop_index(op.f('ix_model_versions_task_type'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_status'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_dataset_id'), table_name='model_versions')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
