"""create knowledge graph entities and relationships tables

Revision ID: f2d9448a7bd6
Revises: 604d1f3c1fb0
Create Date: 2026-08-15 21:58:21.875852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2d9448a7bd6'
down_revision: Union[str, Sequence[str], None] = '604d1f3c1fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kg_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'entity_type', 'name', name='uq_kg_entity_dataset_type_name')
    )
    op.create_index(op.f('ix_kg_entities_dataset_id'), 'kg_entities', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_kg_entities_entity_type'), 'kg_entities', ['entity_type'], unique=False)
    op.create_table('kg_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('subject_entity_id', sa.UUID(), nullable=False),
    sa.Column('predicate', sa.String(length=50), nullable=False),
    sa.Column('object_entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_entity_id'], ['kg_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['kg_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kg_relationships_dataset_id'), 'kg_relationships', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_kg_relationships_object_entity_id'), 'kg_relationships', ['object_entity_id'], unique=False)
    op.create_index(op.f('ix_kg_relationships_subject_entity_id'), 'kg_relationships', ['subject_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kg_relationships_subject_entity_id'), table_name='kg_relationships')
    op.drop_index(op.f('ix_kg_relationships_object_entity_id'), table_name='kg_relationships')
    op.drop_index(op.f('ix_kg_relationships_dataset_id'), table_name='kg_relationships')
    op.drop_table('kg_relationships')
    op.drop_index(op.f('ix_kg_entities_entity_type'), table_name='kg_entities')
    op.drop_index(op.f('ix_kg_entities_dataset_id'), table_name='kg_entities')
    op.drop_table('kg_entities')
    # ### end Alembic commands ###
